name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # setup pnpm
      - name: Setup Node.js
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run prettier:check

      # - name: Lint
      #   run: pnpm run prettier:format
