name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run prettier:check

      # - name: Lint
      #   run: pnpm run prettier:format
